language: cpp
dist: trusty
compiler:
- g++
os:
- linux
  addons:
    apt:
      sources:
        - ubuntu-toolchain-r-test
      packages:
        - g++-6
  env:
    - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"

branches:
  only:
  - master

script:
  - cd src
  - make
