language: cpp
sudo: false
dist: trusty
compiler:
- g++
os:
- linux

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - lcov

branches:
  only:
  - master

script: ./test_script.sh
